### ISSUE TITLE
Why was the instance closed?

### ISSUE THREAD

**Issue by xeruf** [Miaourt/niu-ending#1]
I read that niu.moe was a quite popular instance, and I was considering to switch to Pleroma. It seems you switched to Mastodon on raru.re, but nowhere see an indication why ;)

**Comment by Miaourt** [comment]
Well, there have been announced since 2019, everyone on niu received a mail, and I think I did a long post back then (check your mailbox if you where on niu it)
Tl;dr : too big, too much of a burden for a single person :p

**Comment by xeruf** [comment]
Okidoke, no I was never on there, just curious as I am currently exploring the fediverse and would like to hear testimonies of people who switched from Pleroma to Mastodon and why since I am considering a move in the other direction.
